### PR TITLE
Make Myself Responsible for Once

### PR DESCRIPTION
**Pull request by leycec**
By [popular demand](https://github.com/conda-forge/pydot-feedstock/pull/2#issuecomment-413569448), this pull request elevates my volunteer privileges to that of somebody responsible for something for once. Reluctantly, I think this makes me a co-maintainer of this feedstock. I can already feel the beads of sweat pooling around my armpits.

@nehaljwani, the existing feedstock maintainer, is already doing a splendid job [from somewhere in the Milky Way Galaxy](https://github.com/nehaljwani). Aside from also residing in the Milky Way Galaxy, I'm unsure what else I can offer. I'll probably just end up being the [bothersome albatross around his neck](http://www.victorianweb.org/art/illustration/wehnert/34.jpg), but hope for happier outcomes.

For safety, I'll continue to ask for peer review on significant changesets. For trivial changesets (e.g., version bumps), I'll avoid pestering others and just quietly merge the pull requests in question myself.

If that and more sounds good, sign me up for additional unwanted responsibilities! ...*sigh.*

<sup>Why do I do this to myself.</sup>

### CODE REVIEW

**Comment by leycec** [comment]
**Wait.** Appveyor failed. What the...

**EDIT:** Looks like an [ignorable Appveyor download failure](https://ci.appveyor.com/project/conda-forge/pydot-feedstock/build/1.0.10/job/d6rtpdk948mowb38). Because Windows and robustness are two concepts whose intersection is the empty set.

**Comment by nehaljwani** [comment]
@conda-forge-admin please re-render

**Comment by nehaljwani** [comment]
I can see you here now: https://github.com/orgs/conda-forge/teams/pydot/members

Mission Accomplished.

**Comment by ocefpaf** [comment]
Thanks to both of you for taking care of this recipe!

**Comment by leycec** [comment]
Thanks a bunch, @nehaljwani. You are the mystical narwhal of the conda-forge community. :dolphin: 

I shall stop bothering everyone now.

**Pull request merged**
